::##GIT ARCHIVE for DATA ESCROW 
SET REPO_NAME=acafiling
SET GITPROJ=plat
SET PROJ=\\denver2\escrow\rawexport
SET EXPPATH=e:\e
SET MM=%DATE:~4,2%
SET DD=%DATE:~7,2%
SET YYYY=%DATE:~10,4%
SET FILE_NAME=TEST-%REPO_NAME%_%YYYY%-%MM%-%DD%
SET LOGFILE=%REPO_NAME%.log
ECHO #%YYYY%:%MM%:%%DD% > %LOGFILE%
ECHO %YYYY%:%MM%:%%DD%:%TIME% START CLONE of %REPO_NAME% >>  %LOGFILE%
git clone ssh://git@devgit.dev.us.corp:7999/%GITPROJ%/%REPO_NAME%.git %REPO_NAME%
ECHO %YYYY%:%MM%:%%DD%:%TIME% CLONE COMPLETE of %REPO_NAME% >  %LOGFILE%
cd %REPO_NAME%
ECHO %YYYY%:%MM%:%%DD%:%TIME% START EXPORT of %REPO_NAME% >>  %LOGFILE%
git archive --format zip --output %EXPPATH%\%FILE_NAME%.zip master
ECHO %YYYY%:%MM%:%%DD%:%TIME% EXPORT COMPLETE of %REPO_NAME% >>  %LOGFILE%
ECHO %YYYY%:%MM%:%%DD%:%TIME% START COPY TO SHARE of %REPO_NAME% >>  %LOGFILE%
copy /B %EXPPATH%\%FILE_NAME%.zip %PROJ%
ECHO %YYYY%:%MM%:%%DD%:%TIME% COPY COMPLETE of %REPO_NAME% >>  %LOGFILE%
:FINALCOPY
echo Exported Repo %REPO_NAME% as %FIE_NAME% in %PROJ%

SET P1=\\denver2\escrow\betaexport
copy %PROJ%\%FILE_NAME%.zip "%P1%"

:END
